# Identificação e Porta
spring.application.name=notificacao
server.port=8081

# O diferencial do Java 21: Threads Leves
spring.threads.virtual.enabled=true

# Configuração do Kafka (Producer e Consumer)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificacao-group
spring.kafka.consumer.auto-offset-reset=earliest

# Serialização JSON (Essencial para o DTO funcionar)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=notificacao.dto

# Configuração do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Observabilidade básica (Actuator)
management.endpoints.web.exposure.include=health,info,metrics
